### ISSUE TITLE
> mpirun -n 4 python parallel_thresholds.py get random results

### ISSUE THREAD

**Issue by zeyunZhao** [wmglab-duke/cajal#3]
I followed your guiudance and installed the totally same environments. But I got random results when I run parallel_thresholds.py in32 CPUs many times (about 2/10 are abnormal results). Is it normal or not?

Any reply will be appreciated.

![image](https://github.com/user-attachments/assets/b6901932-fba2-4397-945b-e96bab6563c7)

**Comment by minhajh** [comment]
This looks like an MPI error. How many physical cores do you have? Does this only occur when you oversubscribe (i.e. mpirun -n 'x' where x > number of physical cores)?

**Comment by zeyunZhao** [comment]
It seems like that I can get the same results 10 times when I run this code in 1 CPU

**Comment by minhajh** [comment]
Ah I see. I assumed you were running the file `parallel_thresholds.py` multiple times, not executing code in a for loop. If you check `parallel_thresholds.py`, you'll notice that the plotting code comes after a check statement: `if MPI.MASTER(): ...plotting code etc.`. This is not by accident. The thresholds are only reassembled on the 'master' rank - on the other ranks, `env.thresholds` is an uninitialized array. If you run your code so that only the master rank generates the plot, i.e. 
```python
for k in range(10):
    N.tstop = 5 * ms
    N.dt = 0.005 * ms
    mrg = MRG etc...
    if MPI.MASTER():
        plt.plot(...)
        plt.savefig(...)
``` 
then it should work as expected.

**Comment by zeyunZhao** [comment]
Yes, I have tried this ten times and got the same results. Does it mean that cajal can run normally? Then why I cannot generate data in axonml well ? The data generated in axonml always have nan. Could you help me with that?

**Comment by zeyunZhao** [comment]
Hello&nbsp;Minhaj,


Happy Thanksgiving!&nbsp;


I am sorry for bothering you. I would like to ask if it is possible for us to have a zoom meeting recently to talk about the problems that I am facing in reproducing your work 'axonml'? Me and my PI are very interesting in your amazing work and really want to use it for further research.&nbsp;

Looking forward to your reply.


Best,
Zeyun Zhao




zeyunZhao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wmglab-duke/cajal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月21日(星期四) 凌晨0:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wmglab-duke/cajal] &gt; mpirun -n 4 python parallel_thresholds.py get random results (Issue #3)





 
This looks like an MPI error. How many physical cores do you have? Does this only occur when you oversubscribe (i.e. mpirun -n 'x' where x &gt; number of physical cores)?

**Comment by minhajh** [comment]
My guess is that the issues with recording (https://github.com/wmglab-duke/axonml/issues/6) are due to improper configuration of parallel HDF5 on your end. #89ebfda prevents the recording backend from defaulting to the 'mpio' driver if the # ranks < 2. Pull the latest commit and see if you can generate NaN-free data with `mpirun -n 1`.

You can send me an email directly (minhaj.hussain[at]duke[dot]edu) and we can look into setting up a meeting.

**Comment by minhajh** [comment]
Earlier commit introduced a bug when using hdf5 recording & 1 process. 48235ac resolves this. Try pulling the latest commit and see if you can generate NaN-free data with mpirun -n 1.

**Comment by zeyunZhao** [comment]
I have tried, but there is still nan in data.

**Comment by zeyunZhao** [comment]
![image](https://github.com/user-attachments/assets/d23527b3-f453-41db-90f0-63047a8b0fcd)

**Comment by zeyunZhao** [comment]
When I reinstall it by: conda install -c conda-forge "h5py>=2.9=mpi*"; I got the results:

![image](https://github.com/user-attachments/assets/b2ab3844-6961-45f4-949c-0883bacfa114)

**Comment by minhajh** [comment]
I think this is resolved (https://github.com/wmglab-duke/axonml/issues/6). Closing the issue.
